spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 'a7ee174a '
    url: jdbc:mysql://localhost:3306/heroku_b9de4e3d35c34b8
    username: bda411683172e7
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
